# Generated by Django 4.0.2 on 2022-04-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0004_notification_delete_notificaton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
